name: automatic grader

on:
  workflow_dispatch:  # Allow manual workflows runs
    inputs:
      test_py_parameters:
        description: 'Parameters to pass to python test.py (optional)'
        required: false
        default: ''
      correct_results:
        description: 'url to download correct results'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: 3.8

    - name: Install dependencies and start Ray
      run: |
        pip install -r requirements.txt
        ray stop  # Ensure any previous instance of Ray is stopped
        ray start --head --object-store-memory=5500000000

    - name: download the data
      run:  |
        sudo apt-get update
        sudo apt-get install git-lfs
        git lfs install
        git clone https://huggingface.co/datasets/tttjjj/cs511p2_data
        mv cs511p2_data/correct_results.zip ./
        mv cs511p2_data/tables.zip ./
        unzip tables.zip
        unzip correct_results.zip

    - name: run the grader using test.py
      run: python test.py ${{ github.event.inputs.test_py_parameters }}
