name: test correctness

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu
    strategy:
      fail-fast: false

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2  # Check out your repository's codes

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: 3.8

    - name: Install dependencies and start Ray
      run: |
        pip install -r requirements.txt
        ray stop  # Ensure any previous instance of Ray is stopped
        ray start --head --object-store-memory=5500000000

    - name: download the data
      run:  |
        gdown https://drive.google.com/drive/u/1/folders/1SfJhSPCvUfHI2Vc_toVZIIzz1_50LpOx -O . --folder
        gdown https://drive.google.com/drive/u/1/folders/10Rx3yLCJ5VTXuqJe_2ZuKzRiDSzlV3A0 -O . --folder
        unzip tables.zip
        unzip correct_results.zip

    - name: run the grader using test.py
      run: python test.py
